name: libTriangle
version: 0.0.1
description: >-
  Trying to call a custom C library from Dart with some FFI help
author: Umberto Sonnino <umberto@rive.app>
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  ffi: ^0.1.3
# dev_dependencies:
#   test: ^1.5.3